variables:
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: "-ffdx"

stages:
  - lint
  - deploy-acceptance-ansible
  - test-acceptance
  - deploy-production-nginx

include:
  - component: $CI_SERVER_FQDN/rse/docker/images/sphinx-doc/sphinx-doc@2.3.1
    inputs:
      stage: build
      dir: docs
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - docs/source/**/*

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-lint@10.2.6
    inputs:
      stage: lint
      dir: ansible

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-deploy@10.2.6
    inputs:
      stage: deploy-acceptance-ansible
      dir: ansible
      inventory: gesis-acceptance
      playbook: gesis.yml
      ssh-user: ansible
      ssh-key-type: ed25519

.smoke test:
  stage: test-acceptance
  variables:
    INTERACTIVE_URL: url
  script:
    - curl $INTERACTIVE_URL

smoke test to acceptance cluster:
  stage: test-acceptance
  variables:
    INTERACTIVE_URL: https://notebooks-test.gesis.org/binder/
  extends:
    - .smoke test
