variables:
  GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: "-ffdx"

# This workflow:rules are required to enable merge request pipelines!
workflow:
  rules:
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_TAG
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - build
  - deploy-acceptance-ansible
  - test-acceptance
  - deploy-production-nginx

include:
  - component: $CI_SERVER_FQDN/rse/docker/images/sphinx-doc/sphinx-doc@2.3.1
    inputs:
      stage: build
      dir: docs
    rules:
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - docs/source/**/*

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-lint@11.1.0
    inputs:
      stage: lint
      dir: ansible
    rules:
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - ansible/**/*

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-deploy@11.1.0
    inputs:
      stage: deploy-acceptance-ansible
      environment: acceptance
      dir: ansible
      inventory: gesis-acceptance
      playbook: gesis.yml
      ssh-user: ansible
      ssh-key-type: ed25519
    rules:
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == "merge_request_event"
        changes:
          - ansible/**/*

.smoke test:
  stage: test-acceptance
  variables:
    INTERACTIVE_URL: url
  script:
    - curl $INTERACTIVE_URL

smoke test to acceptance cluster:
  stage: test-acceptance
  rules:
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    INTERACTIVE_URL: https://notebooks-test.gesis.org/binder/
  extends:
    - .smoke test

pages:
  stage: .post
  rules:
    - if: $CI_SERVER_FQDN == "git.gesis.org" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo Publish documentation to GitLab Pages
  artifacts:
    paths:
      - public
