- name: Add a Cert Manager Helm repository
  kubernetes.core.helm_repository:
    repo_name: jetstack
    repo_url: https://charts.jetstack.io
    force_update: true
- name: Create Cert Manager Kubernetes namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
- name: Deploy Cert Manager
  kubernetes.core.helm:
    release_name: cert-manager
    release_namespace: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: '{{ cert_manager_version }}'
    create_namespace: false
    history_max: 3
    values:
      crds:
        enabled: true
- name: Create a Cluster Issuer
  kubernetes.core.k8s:
    state: present
    definition:
      CapiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt
      spec:
        acme:
          server: '{{ cert_manager_production | ternary(cert_manager_letsencrypt_production, cert_manager_letsencrypt_stage) }}'
          email: '{{ cert_manager_email }}'
          privateKeySecretRef:
            name: letsencrypt
          solvers:
            - http01:
                ingress:
                  # Don't change the ingressClassName
                  ingressClassName: nginx
