- name: Disable SWAP since kubernetes can't work with swap enabled
  ansible.builtin.command: swapoff -a
  changed_when: false
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
- name: Disable Firewall
  ansible.builtin.command: ufw disable
  changed_when: false
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - curl
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Install K3s
  when: ('k3s' not in ansible_facts.services)
  ansible.builtin.import_tasks:
    file: k3s.yml
- name: Make sure K3s is running
  ansible.builtin.systemd_service:
    enabled: true
    name: k3s
    state: started
