- name: Create directory
  ansible.builtin.file:
    state: directory
    path: /home/ansible/bin
    owner: ansible
    group: ansible
    mode: u=rwx,g=rwx,o=rx
- name: Copy kill-after-timeout-pods.py
  ansible.builtin.copy:
    src: files/cron/kill-after-timeout-pods.py
    dest: /home/ansible/bin/kill-after-timeout-pods.py
    owner: ansible
    group: ansible
    mode: u=rwx,g=rwx,o=r
- name: Add cron job to remove timed out pods
  ansible.builtin.cron:
    name: "remove timeout"
    job: "python3 /home/ansible/bin/kill-after-timeout-pods.py --verbose >> /home/ansible/kill-after-timeout-pods.log 2>&1"
    minute: "*/5"