- name: Create directory
  ansible.builtin.file:
    state: directory
    path: /home/ansible/bin
    owner: ansible
    group: ansible
    mode: u=rwx,g=rwx,o=rx
- name: Copy kill-succeeded-pods.py
  ansible.builtin.copy:
    src: files/cron/kill-succeeded-pods.py
    dest: /home/ansible/bin/kill-succeeded-pods.py
    owner: ansible
    group: ansible
    mode: u=rwx,g=rwx,o=r
- name: Add cron job to remove succeeded pods
  ansible.builtin.cron:
    name: "remove succeeded"
    job: "python3 /home/ansible/bin/kill-succeeded-pods.py --verbose >> /home/ansible/kill-succeeded-pods.log 2>&1"
    minute: "*/5"
