- name: Copy orc2-fix-jupyterhub-bot Python script
  ansible.builtin.copy:
    src: files/usr/bin/orc2-fix-jupyterhub-bot.py
    dest: /usr/bin/orc2-fix-jupyterhub-bot.py
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r
- name: Copy orc2-fix-jupyterhub-bot Systemd Unit script
  ansible.builtin.copy:
    src: files/etc/systemd/system/orc2-fix-jupyterhub-bot.service
    dest: /etc/systemd/system/orc2-fix-jupyterhub-bot.service
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r
- name: Enable service orc2-fix-jupyterhub-bot
  ansible.builtin.systemd:
    name: orc2-fix-jupyterhub-bot
    daemon_reload: true
    enabled: true
    masked: false
    state: restarted
