- name: Download K3s installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-installation.sh
    owner: '{{ ansible_facts.real_user_id }}'
    group: '{{ ansible_facts.real_group_id }}'
    mode: u=rwx,g=rwx,o=rwx
- name: Run K3s installation script
  ansible.builtin.script: /tmp/k3s-installation.sh
