- name: Check if Kubernetes is running
  ansible.builtin.shell: >
    kubectl get nodes || /bin/true
  changed_when: false
  register: kubernetes_nodes
- name: Pull kubernetes images
  when: kubernetes_nodes.stdout.find('control-plane') == -1
  ansible.builtin.shell: >
    kubeadm config images pull
    --cri-socket unix:///run/containerd/containerd.sock
  changed_when: false
- name: Initialize the cluster
  when: kubernetes_nodes.stdout.find('control-plane') == -1
  ansible.builtin.shell: >
    kubeadm init
    --pod-network-cidr=10.244.0.0/16
    --upload-certs
    --control-plane-endpoint={{ K8S_CONTROL_PLANE_ENDPOINT }}
    --cri-socket unix:///run/containerd/containerd.sock
  changed_when: false
  register: kubeadm_init_output
- name: Create root's .kube directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
- name: Copies admin.conf to root's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: u=rw,g=r,o=
- name: Create user's .kube directory
  ansible.builtin.file:
    path: /home/ansible/.kube
    state: directory
    mode: u=rwx,g=x,o=x
    owner: ansible
    group: ansible
- name: Copies admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: true
    owner: ansible
    group: ansible
    mode: u=rw,g=,o=
- name: Get the token for joining the worker nodes
  ansible.builtin.shell: >
    kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command
- name: Create temporary file
  ansible.builtin.file:
    path: /tmp/kubernetes_join_command
    state: touch
    owner: ansible
    group: ansible
    mode: u=rw,g=r,o=
- name: Save content of join command
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      {{ kubernetes_join_command.stdout }}
    dest: /tmp/kubernetes_join_command
    owner: ansible
    group: ansible
    mode: u=rw,g=r,o=
- name: Copy join command to local file
  ansible.builtin.fetch:
    src: /tmp/kubernetes_join_command
    dest: "{{ ANSIBLE_CONTROL_NODE_TMP }}"
- name: Add Container Network Interface (CNI) to Kubernetes cluster
  ansible.builtin.import_tasks:
    file: cni.yml
- name: Add GitLab Helm repository
  kubernetes.core.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io
- name: Deploy GitLab agent
  kubernetes.core.helm:
    name: "gitlab-agent-{{ inventory_file | basename }}"
    chart_ref: gitlab/gitlab-agent
    release_namespace: gitlab-agent
    dependency_update: true
    create_namespace: true
    set_values:
      - value: "config.token={{ GITLAB_K8S_TOKEN }}"
      - value: config.kasAddress=wss://git.gesis.org/-/kubernetes-agent/
