- name: Configure servers that are part of Kubernetes cluster
  hosts: all
  gather_facts: false
  become: true
  roles:
    - k8s-common
- name: Configure Kubernetes control panel
  hosts: kubernetes_control_panel
  gather_facts: false
  become: true
  roles:
    - role: k8s-control-panel
- name: Configure Kubernetes workers
  hosts: kubernetes_workers
  gather_facts: false
  become: true
  roles:
    - k8s-worker
- name: Configure Kubernetes Cluster Network
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: cni
    - role: metallb
      vars:
        metallb_addresses_begin: '{{ K8S_INGRESS }}'
        metallb_addresses_end: '{{ K8S_INGRESS }}'
    - ingress
    # The cert-manager only works after the ingress.
    - role: cert-manager
      vars:
        cert_manager_email: methodshub@gesis.org
        cert_manager_production: '{{ CERT_MANAGER_PRODUCTION }}'
- name: Configure External Access to Kubernetes Cluster
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: gitlab
      vars:
        gitlab_k8s_token: '{{ GITLAB_K8S_TOKEN }}'
- name: Configure Conainer Registry on Kubernetes cluster
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: harbor
      vars:
        harbor_state: '{{ HARBOR_STATE }}'
        harbor_storage_class_name: local-storage
        harbor_protocol: https
        harbor_domain: '{{ HARBOR_DOMAIN }}'
        harbor_path: '{{ HARBOR_PATH }}'
        harbor_root_password: '{{ HARBOR_ADMIN_PASSWORD }}'
    - role: nexus
      vars:
        nexus_state: '{{ NEXUS_STATE }}'
        nexus_storage_class_name: local-storage
        nexus_protocol: https
        nexus_domain: '{{ NEXUS_DOMAIN }}'
        nexus_path: '{{ NEXUS_PATH }}'
        nexus_registry_domain: '{{ NEXUS_REGISTRY_DOMAIN }}'
        nexus_registry_path: '{{ NEXUS_REGISTRY_PATH }}'
        nexus_root_password: '{{ NEXUS_ADMIN_PASSWORD }}'
- name: Prepare Kubernetes cluster for mybinder.org
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: prometheus
      vars:
        prometheus_capacity_storage: '{{ PROMETHEUS_CAPACITY_STORAGE }}'
        prometheus_storage_class: local-storage-prometheus
        prometheus_storage_local_path: /orc2_data/prometheus
    - role: grafana
      vars:
        grafana_capacity_storage: '{{ GRAFANA_CAPACITY_STORAGE }}'
        grafana_storage_class: local-storage-grafana
        grafana_storage_local_path: /orc2_data/grafana
    - role: jupyterhub
      vars:
        jupyterhub_capacity_storage: '{{ JUPYTERHUB_CAPACITY_STORAGE }}'
        jupyterhub_storage_class: local-storage-jupyterhub
        jupyterhub_storage_local_path: /orc2_data/jupyterhub
    - role: interactive-environment
      vars:
        interactive_environment_domain: '{{ INTERACTIVE_ENVIRONMENT_DOMAIN }}'
