- name: Configure servers that are part of Kubernetes cluster
  hosts: all
  gather_facts: false
  become: true
  roles:
    - k8s-common
- name: Configure Kubernetes control panel
  hosts: kubernetes_control_panel
  gather_facts: false
  become: true
  roles:
    - role: k8s-control-panel
      vars:
        k8s_control_panel_addresses_begin: '{{ K8S_INGRESS }}'
        k8s_control_panel_addresses_end: '{{ K8S_INGRESS }}'
- name: Configure Kubernetes workers
  hosts: kubernetes_workers
  gather_facts: false
  become: true
  roles:
    - k8s-worker
- name: Configure Harbor on Kubernetes cluster
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: harbor
      vars:
        harbor_domain: '{{ HARBOR_DOMAIN }}'
        harbor_path: '{{ HARBOR_PATH }}'
- name: Prepare Kubernetes cluster for mybinder.org
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - role: prometheus
      vars:
        prometheus_capacity_storage: 1Gi
        prometheus_storage_class: local-storage
        prometheus_storage_local_path: /orc2_data/prometheus
    - role: grafana
      vars:
        grafana_capacity_storage: 1Gi
        grafana_storage_class: local-storage
        grafana_storage_local_path: /orc2_data/grafana
    - role: jupyterhub
      vars:
        jupyterhub_capacity_storage: 1Gi
        jupyterhub_storage_class: local-storage
        jupyterhub_storage_local_path: /orc2_data/jupyterhub
    - mybinder
