- name: Create directory /etc/apt/trusted.gpg.d if it does not exist
  ansible.builtin.file:
    state: directory
    path: /etc/apt/trusted.gpg.d
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
- name: Add Docker public GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
    force: true
- name: Add Docker source
  ansible.builtin.apt_repository:
    update_cache: false
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present
