- name: Create directory /etc/apt/trusted.gpg.d if it does not exist
  ansible.builtin.file:
    state: directory
    path: /etc/apt/trusted.gpg.d
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
- name: Remove old Kubernetes public GPG key
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    state: absent
- name: Remove old Kubernetes public GPG key
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.asc
    state: absent
- name: Remove old Kubernetes repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
    state: absent
- name: Remove old Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ item }}/deb/ /"
    filename: kubernetes
    state: absent
  loop:
    - '1.27'
    - '1.28'
    - '1.29'
    - '1.30'
    - '1.31'
    - '1.32'
- name: Download Kubernetes public GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_common_kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/trusted.gpg.d/kubernetes.asc
    mode: "0644"
    force: true
- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_common_kubernetes_version }}/deb/ /"
    filename: kubernetes
    state: present
