- name: Add GitLab Helm repository
  kubernetes.core.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io
    force_update: true
- name: Create GitLab namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: gitlab-agent
- name: Deploy GitLab agent
  kubernetes.core.helm:
    release_name: "gitlab-agent-{{ inventory_file | basename }}"
    release_namespace: gitlab-agent
    chart_ref: gitlab/gitlab-agent
    chart_version: '{{ gitlab_version }}'
    create_namespace: false
    values:
      image:
        tag: '{{ gitlab_tag }}'
      config:
        token: '{{ gitlab_k8s_token }}'
        kasAddress: wss://git.gesis.org/-/kubernetes-agent/
