cert_manager_version: v1.16.3
cert_manager_email: to-overwrite@mail
cert_manager_production: false
cert_manager_letsencrypt_production: https://acme-v02.api.letsencrypt.org/directory
cert_manager_letsencrypt_stage: https://acme-staging-v02.api.letsencrypt.org/directory
